2019-01-04 14:18:03,668 ERROR: Exception on /auth/login [GET] [in c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\auth\routes.py", line 29, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\base.html", line 16, in template
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
TemplateSyntaxError: expected token ',', got 'main'
2019-01-04 14:18:23,063 ERROR: Exception on /auth/login [GET] [in c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\auth\routes.py", line 29, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\base.html", line 16, in template
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
TemplateSyntaxError: expected token ',', got 'main'
2019-01-04 14:19:09,897 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:71]
2019-01-04 14:19:14,846 ERROR: Exception on /auth/login [GET] [in c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\auth\routes.py", line 29, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\supratimdas\pycharmprojects\flask_tutorials\flask_tutorials\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\templates\base.html", line 16, in template
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
TemplateSyntaxError: expected token ',', got 'main'
2019-01-04 14:20:18,880 INFO: Microblog startup [in C:\Users\supratimdas\PycharmProjects\Flask_Tutorials\app\__init__.py:71]
