2018-12-23 18:37:21,224 ERROR: Exception on /favicon.ico [GET] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
TypeError: not_found_error() takes no arguments (1 given)
2018-12-23 18:37:30,301 ERROR: Exception on /favicon.ico [GET] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
TypeError: not_found_error() takes no arguments (1 given)
2018-12-23 18:37:34,485 ERROR: Exception on /favicon.ico [GET] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
TypeError: not_found_error() takes no arguments (1 given)
2018-12-23 18:37:37,048 ERROR: Exception on /favicon.ico [GET] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
TypeError: not_found_error() takes no arguments (1 given)
2018-12-23 18:37:39,116 ERROR: Exception on /favicon.ico [GET] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
TypeError: not_found_error() takes no arguments (1 given)
2018-12-23 18:37:41,030 ERROR: Exception on /favicon.ico [GET] [in /Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/Supra/PycharmProjects/Flask_Tutorials/venv/lib/python2.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
TypeError: not_found_error() takes no arguments (1 given)
2018-12-23 21:13:00,581 INFO: Microblog startup [in /Users/Supra/PycharmProjects/Flask_Tutorials/app/__init__.py:49]
2018-12-23 21:13:01,167 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:02,004 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:02,689 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:03,286 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:03,902 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:04,516 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:05,120 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:05,732 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:06,339 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:07,927 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:08,509 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:09,104 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:09,685 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:10,258 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:10,857 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:11,447 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:12,023 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:12,601 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:13,177 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:13,785 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:14,365 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:14,942 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:15,513 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:16,088 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:16,673 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:17,261 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:17,844 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:18,429 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:19,427 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:20,024 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:20,595 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:21,201 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:21,828 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:22,457 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:23,091 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:23,672 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:24,304 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:24,920 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:25,544 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:26,167 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:26,744 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:27,289 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:27,859 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:28,435 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:29,022 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:29,621 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:30,210 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:30,820 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:31,509 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:32,096 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:32,682 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:33,295 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:33,909 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:34,575 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:35,160 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:35,755 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:36,325 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:36,915 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:37,518 INFO: Microblog startup [in ./app/__init__.py:49]
2018-12-23 21:13:38,110 INFO: Microblog startup [in ./app/__init__.py:49]
